[workspace]
default-members = ["odilia"]
members = [
	"cache",
  "common",
  "input",
  "odilia",
  "sohkd",
]

[profile.release]
lto = true
codegen-units = 1 # Reduce codegen units for better optimizations (from swhkd)

[workspace.metadata.release]
allow-branch = ["main"]
# By default, crates will not be released or published
# These are overridden on a crate-by-crate basis
release = false
publish = false
shared-version = true
consolidate-commits = true
consolidate-pushes = true
pre-release-commit-message = "Release Odilia version {{version}}"
post-release-commit-message = "Post release version bump: version {{next_version}}"
tag-message = "{{crate_name}} version {{version}}"
dev-version-ext = "dev"
dev-version = true
pre-release-hook = ["cargo", "fmt"]
dependent-version = "upgrade"

[workspace.dependencies]
atspi = { version = "0.11.0", features = ["tokio", "unstable-traits"] }
eyre = "0.6.8"
nix = "0.25.0"
serde_json = "1.0.89"
ssip-client = { default-features = false, features = ["tokio"], git = "https://gitlab.com/TTWNO/ssip-client" }
tokio = { version = "^1.22.0", default-features = false, features = ["sync", "macros", "rt", "signal", "tracing"] }
tracing = "^0.1.37"
tracing-log = "^0.1.3"
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["env-filter", "parking_lot"] }
tracing-error = "^0.2.0"
tracing-tree = "^0.2.2"
zbus = { version = "^3.6.2", default-features = false, features = ["tokio"] }
serde_plain = "1.0.1"

